export declare const accent: string;
export declare const container: string;
export declare const disabled: string;
export declare const fullSize: string;
export declare const large: string;
export declare const outlined: string;
export declare const primary: string;
export declare const pure: string;
export declare const small: string;
